@startuml

package Common{
    class InputManager{
        -keyActions : UnityEvent
    }
}

package InGame{
    package Roads{
        class Road{
            +connectedJoints : RoadJoint[]
            -length : float
            -lanes : int
            +cost : float
            -edgeTrafficLight : TrafficLight[]
            -OptimizeArrangement() : void
            -ModelizeCost() : float
            -GetJoints() : void
        }

        class RoadJoint{
            +connectedRoads : Road[]
            +RegisterConnection() : void
        }

        Road - RoadJoint

        class Intersection{
            -trafficLightsSystem : TrafficLightsSystem
            +ChangeAllowance() : void
        }

        RoadJoint <|-- Intersection

        class OutsideConnection{
            +spawnPossibility : float
        }

        RoadJoint <|-- OutsideConnection

        class TrafficLightsSystem{
            -trafficLights : TrafficLight[]
            +correspondingTrafficLight : Dictionary<Road, TrafficLight>
            +ChangeDirection() : void
            -GetTrafficLight : void
        }

        Intersection o-- TrafficLightsSystem

        class TrafficLight{
            -lightColor : enum
            +ToggleLight() : void
        }

        TrafficLightsSystem o-- TrafficLight
        Road o-- TrafficLight

        InputManager -- TrafficLightsSystem
    }
    
    class Car{
        -destination : OutsideConnection
        -drivingTime : float
        -Run() : void
        -Turn() : void
    }

    Car --> Roads

    class CarGenerator{
        -carLimit : int
        -outsideConnections : OutsideConnection[]
        -appearingCars : Car[]
        -GetOutsideConnection() : void
        -SpawnCar() : void
    }

    CarGenerator --> Car
    CarGenerator --> OutsideConnection

    package Managers{
        class UIManagerInGame{
            -UpdateUIs() : void
        }

        class GameManagerInGame{
            +sequence : enum
            +score : int
            +timeLeft : float
            +AddPoint() : void
        }
    }
}

@enduml